wiki/main/urls.py
from django.urls import path


from .views import home, other, add_article, ALogin, ALogout, UserRegView
from .views import UserPassResetView, UserPassResetDone, UserPassResetConfirmView
from .views import ChangeUserInfo, ChangeUserPass, DeleteUserView, article_change_staff, article_delete
from .views import article_detail, comment_delete, article_change_user, edit_list
from .views import edit_detail, by_rubric

urlpatterns = [



	# urls home amd other
	path('', home, name = 'home'), # урл которые показывает начальную страницу
	path('other/<str:page>/', other, name = 'other'), # урл который будет выводить бумаги какие-то



	# urls for articles
	path('article/add_article/', add_article, name = 'add_article'),
	path('article/article_change_staff/<int:pk>/', article_change_staff, name = 'change_staff'),
	path('article/article_change_user/<int:pk>/', article_change_user, name = 'article_change_user'),
	path('article/article_delete/<int:pk>/', article_delete, name = 'article_delete'),
	path('article/detail/<int:pk>/', article_detail, name = 'article_detail'),
	path('article/rubric/<int:pk>', by_rubric, name = 'by_rubric'),


	# urls for users
	path('user/login/', ALogin.as_view(), name = 'login'),
	path('user/logout/', ALogout.as_view(), name = 'logout'),
	path('user/change_user_info/', ChangeUserInfo.as_view(), name = 'changeuserinfo'),
	path('user/chang_euser_pass/', ChangeUserPass.as_view(), name = 'changeuserpass'),
	path('user/delete_user/', DeleteUserView.as_view(), name ='deleteuser'),


	# urls for register user
	path('user/register/', UserRegView.as_view(), name = 'register'),



	# urls for password reset
	path('profile/password_reset_form/', UserPassResetView.as_view(), name = 'password_reset_form'),
	path('profile/password_reset_done/', UserPassResetDone.as_view(), name = 'password_reset_done' ),
	path('profile/password_reset_confirm/<uidb64>/<token>/', UserPassResetConfirmView.as_view(), name = 'password_reset_confirm'),

	# urls for comments
	path('article/comments/delete/<int:pk>', comment_delete, name = 'comment_delete'),

	# urls for edit article
	path('article/edit_list/<int:pk>', edit_list, name = 'edit_list'),
	path('article/edit_detail/<int:pk>', edit_detail, name = 'edit_detail'),




]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import never_cache
from django.contrib.staticfiles.views import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace = 'main')),
    path('social/', include('social_django.urls', namespace = 'social')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', 
        never_cache(serve)))

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wiki/main/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column, MultiField, Button, Field
from django.forms import inlineformset_factory, modelformset_factory
from django.forms.models import formset_factory
from django.contrib.auth.models import User
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError

from .models import Article, AdditionalImage, Comment

# for articles
class ArticleForm(forms.ModelForm):
	# Я около 5 часов пытался сделать нормально вместе с наборами форм но у меня не получилось
	# def __init__(self, *args, **kwargs):
	# 	super().__init__(*args, **kwargs)
	# 	self.helper = FormHelper()
	# 	self.helper.layout = Layout(
	# 		Row(
	# 			Column('title', css_class = 'form-group col-md-6 mb-0'),
	# 			Column('rubric', css_class = 'form-group col-md-4 mb-0'),
	# 			Column('street', css_class = 'form-group col-md-2 mb-0'),
	# 			css_class = 'form-row'),

	# 		'content',
	# 		'image',
			
	# 		)

	class Meta:
		model = Article
		fields = ('rubric','title','street','content','image')
		widgets = {'created_at' : forms.HiddenInput, 'street' : forms.TextInput(attrs = {'placeholder':'Ул: [Д: Кв: (если нужно)]'})}
AIFormSet = inlineformset_factory(Article, AdditionalImage, fields = '__all__')

# for User
class UserRegForm(forms.ModelForm):
	email = forms.EmailField(
		required = True,
		label = 'Электронная почта')

	pass1 = forms.CharField(
		label = 'Пароль',
		widget = forms.PasswordInput,
		help_text = password_validation.password_validators_help_text_html())

	pass2 = forms.CharField(
		label = 'Повторите пароль',
		widget = forms.PasswordInput,
		help_text = password_validation.password_validators_help_text_html())

	def clean(self):
		passw1 = self.cleaned_data['pass1']
		if passw1:
			password_validation.validate_password(passw1)
		super().clean()
		passw2 = self.cleaned_data['pass2']
		if passw1 and passw2 and passw1 != passw2:
			errors = {'pass2' : ValidationError(
				'Введенные пароли не совпадают, попробуйте ещё раз',
				code = 'password_missmatch')}
			raise ValidationError(errors)

	def save(self, commit = True):
		user = super().save(commit = False)
		user.set_password(self.cleaned_data['pass1'])
		if commit:
			user.save()
		return user

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.layout = Layout(
			Row(
				Column('username', css_class = 'form-group col-md-6 mb-0'),
				Column('email', css_class = 'form-group col-md-4 mb-0'),
				css_class = 'form-row'),

			Row(
				Column('pass1', css_class = 'form-group col-md-4 mb-0'),
				Column('pass2', css_class = 'form-group col-md-4 mb-0'),
				css_class = 'form-row'),
			
			Row(
				Column('first_name', css_class = 'form-group col-md-4 mb-0'),
				Column('last_name', css_class = 'form-group col-md-4 mb-0'),
				css_class = 'form-row'),

			Submit('submit', 'Зарегистрироваться'))

	class Meta:
		model = User
		fields = ('username', 'email', 'pass1', 'pass2', 'first_name', 'last_name')	


class ChangeUserInfoForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('username', 'email', 'first_name', 'last_name')

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.layout = Layout(
			Row(
				Column('username', css_class = 'form-group col-md-6 mb-0'),
				css_class = 'form-row'),
			Row(
				Column('email', css_class = 'form-group col-md-6 mb-0'),
				css_class = 'form-row'),
			Row(
				Column('first_name', css_class = 'form-group col-md-4 mb-0'),
				Column('last_name', css_class = 'form-group col-md-4 mb-0'),
				css_class = 'form-row'),
			Submit('submit', 'Сменить', css_class = 'my-3'))

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = '__all__'
		widgets = {'article':forms.HiddenInput, 'author':forms.HiddenInput}

	# def __init__(self, *args, **kwargs):
	# 	super().__init__(*args, **kwargs)
	# 	self.helper = FormHelper()
	# 	self.helper.layout = Layout(
	# 		Field('content', css_class = 'form-group col-md-6 mb-0,'),			
	# 		Submit('submit', 'Оставить комментарий', css_class = 'my-3'))


from .models import EditArticle
class EditArticleForm(forms.ModelForm):
	class Meta:
		model = EditArticle
		fields = ('title', 'content', 'image', 'help_text')
		widgets = {'help_text':forms.TextInput(attrs = {'placeholder':'основные изменения и где они'})}

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.layout = Layout(
			Row(
				Column('title', css_class = 'form-group col-md-6 mb-0'),
				Column('help_text', css_class = 'form-group col-md-6 mb-0'),
				css_class = 'form-row'),
			
			'content',
			'image',

			Submit('submit', 'Редактировать'))

class SearchForm(forms.Form):
	keyword = forms.CharField(
		required = False,
		max_length = 40,
		label = '')

wiki/main/views.py
from django.shortcuts import render
from django.template.loader import get_template
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages
from django.shortcuts import redirect
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.views.generic import CreateView
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required





from .models import Article, Rubric, Comment
from .forms import ArticleForm, AIFormSet, UserRegForm, ChangeUserInfoForm, CommentForm




# views у которых нет определенного разделения
def home(request):
	# будет выводить нлавную страницу
	rubric = get_object_or_404(Rubric, name = 'Новости')
	articles = Article.objects.filter(rubric = rubric)[:10]
	context = {'articles':articles}
	return render(request, 'main/home.html', context)



def other(request, page): 
	# Используется для того чтобы выводить документы различные (ну у меня будут не документы)
	try:
		template = get_template('main/' + page + '.html') # Пытаемся получить шаблон
	except TemplateDoesNotExist: # Если не находит такуб страницу
		raise Http404 # То ошибка 404 (страница не найдена)
	return HttpResponse(template.render(request = request))

from django.db.models import Q
from django.core.paginator import Paginator
from .forms import SearchForm
def by_rubric(request, pk):

	# querysets
	rubric = get_object_or_404(Rubric, pk = pk)
	articles = Article.objects.filter(rubric = rubric)

	# search
	if 'keyword' in request.GET:
		keyword = request.GET['keyword']
		q = Q(title__icontains = keyword) | Q(content__icontains = keyword)
		articles = articles.filter(q)
	else:
		keyword = ''
	form = SearchForm(initial = {'keyword':keyword})

	# paginator
	paginator = Paginator(articles, 4)
	if 'page' in request.GET:
		page_num = request.GET['page']
	else:
		page_num = 1
	page = paginator.get_page(page_num)
	context = {'rubric':rubric, 'page':page, 'articles':page.object_list, 'form':form}
	return render(request, 'main/by_rubric.html', context)



# views связанные с статьями
@staff_member_required
def add_article(request):
	if request.method == 'POST':
		forms = ArticleForm(request.POST, request.FILES)
		if forms.is_valid():
			article = forms.save()
			formset = AIFormSet(request.POST, request.FILES, instance = article)
			if formset.is_valid():
				formset.save()
				messages.add_message(request, messages.SUCCESS, message = 'Статья успешно написана!')
				return redirect('main:home')
	else:
		forms = ArticleForm(initial = {})
		formset = AIFormSet()
	context = {'forms':forms, 'formset':formset}
	return render (request, 'main/add_article.html', context)



@staff_member_required
def article_change_staff(request, pk):
	article = get_object_or_404(Article, pk = pk)
	if request.method == 'POST':
		form = ArticleForm(request.POST, request.FILES, instance = article)
		if form.is_valid():
			article = form.save()
			formset = AIFormSet(request.POST, request.FILES, instance = article)
			if formset.is_valid():
				formset.save()
				messages.add_message(request, messages.SUCCESS, message = 'Статья изменена!')
				return redirect('main:home')
	else:
		form = ArticleForm(instance = article)
		formset = AIFormSet(instance = article)
	context = {'form':form, 'formset':formset}
	return render (request, 'main/article_change_staff.html', context)




@staff_member_required
def article_delete(request, pk):
	article = get_object_or_404(Article, pk = pk)
	if request.method == 'POST':
		article.delete()
		messages.add_message(request, messages.SUCCESS, message = 'Статья удалена')
		return redirect('main:home')
	else:
		context = {'article':article}
		return render (request, 'main/article_delete.html', context)



@login_required(login_url = '/user/login/')
def article_detail(request, pk):
	article = Article.objects.get(pk = pk)
	ai = article.additionalimage_set.all()
	comment = Comment.objects.filter(article = pk)
	initial = {'article':article.pk}
	if request.user.is_authenticated:
		initial['author'] = request.user.username
	form_class = CommentForm
	form = form_class(initial = initial)
	if request.method == 'POST':
		c_form = form_class(request.POST)
		if c_form.is_valid():
			response = c_form.save()
			response.author = request.user.username
			response.save()
			messages.add_message(request, messages.SUCCESS, message = 'Комментарий успешно добавлен')
			return redirect('main:home')
		else:
			form = c_form
			messages.add_message(request, messages.WARNING, message = 'Комментарий не был добавлен')	
	context = {'article' : article, 'ai' : ai, 'comment':comment, 'form':form}
	return render(request, 'main/detail.html', context)



# views login and logout
class ALogin(LoginView):
	template_name = 'main/login.html'
class ALogout(LogoutView):
	template_name = 'main/logout.html'



# views for user
class UserRegView(CreateView):
	model = User
	template_name = 'main/register.html'
	form_class = UserRegForm
	success_url = reverse_lazy('main:login')



class ChangeUserInfo(SuccessMessageMixin, UpdateView, LoginRequiredMixin):
	model = User
	template_name = 'main/change_user_info.html'
	form_class = ChangeUserInfoForm
	success_url = reverse_lazy('main:home')
	success_message = 'Личные данные пользователя были успешно изменены!'

	def dispatch(self, request, *args, **kwargs):
		self.user_id = request.user.pk
		return super().dispatch(request, *args, **kwargs)

	def get_object(self, queryset = None):
		if not queryset:
			queryset = self.get_queryset()
		return get_object_or_404(queryset, pk = self.user_id)



class ChangeUserPass(LoginRequiredMixin, SuccessMessageMixin, PasswordChangeView):
	template_name = 'main/change_pass.html'
	success_url = reverse_lazy('main:home')
	success_message = 'Пароль успешно изменен!'



class DeleteUserView(LoginRequiredMixin, DeleteView, SuccessMessageMixin):
	model = User
	template_name = 'main/delete_user.html'
	success_url = reverse_lazy('main:home')

	def dispatch(self, request, *args, **kwargs):
		self.user_id = request.user.pk
		return super().dispatch(request, *args, **kwargs)

	def post(self, request, *args, **kwargs):
		logout(request)
		messages.add_message(request, messages.SUCCESS, message = 'Пользователь успешно удален!')
		return super().post(request, *args, **kwargs)

	def get_object(self, queryset = None):
		if not queryset:
			queryset = self.get_queryset()
		return get_object_or_404(queryset, pk = self.user_id)



# views for comments
def comment_delete(request, pk):
	comment = get_object_or_404(Comment, pk = pk)
	if request.user.is_staff or request.user.username == comment.author:
		if request.method == 'POST':
			comment.delete()
			messages.add_message(request, messages.SUCCESS, message = 'Комментарий был удален!')
			return redirect('main:home')
		else:
			context = {'comment':comment}
			return render(request, 'main/comment_delete.html', context)
	else:
		raise Http404



# views for password reset
class UserPassResetView(PasswordResetView):
	template_name = 'main/password_reset_form.html'
	subject_template_name = 'email/password_reset_subj.txt'
	email_template_name = 'email/password_reset_body.html'
	success_url = reverse_lazy('main:password_reset_done')
class UserPassResetDone(PasswordResetDoneView):
	template_name = 'main/password_reset_done.html'
class UserPassResetConfirmView(PasswordResetConfirmView):
	template_name = 'main/password_reset_confirm.html'
	success_url = reverse_lazy('main:login')


# views for edit article
from .forms import EditArticleForm
from .models import EditArticle



@login_required(login_url = '/user/login/')
def article_change_user(request, pk):
	article = get_object_or_404(Article, pk = pk)

	form_class = EditArticleForm
	if request.method == 'POST':
		e_form = form_class(request.POST)
		if e_form.is_valid():
			edit = EditArticle.objects.create(
				article = article,
				title = e_form.cleaned_data['title'],
				help_text = e_form.cleaned_data['help_text'],
				content = e_form.cleaned_data['content'],
				image = e_form.cleaned_data['image'])
			edit.save()
			messages.add_message(request, messages.SUCCESS, message = 'Спасибо за правки!')
			return redirect('main:home')
	else:
		form = EditArticleForm(instance = article)
		context = {'form':form}
		return render(request, 'main/article_change_user.html', context)



@staff_member_required
def edit_detail(request, pk):
	edit = get_object_or_404(EditArticle, pk = pk)
	article = get_object_or_404(Article, pk = edit.article.pk)
	form_class = EditArticleForm
	if request.method == 'POST':
		e_form = form_class(request.POST)
		if e_form.is_valid():
			article.title = e_form.cleaned_data['title']
			article.content = e_form.cleaned_data['content']
			if e_form.cleaned_data['image']:
				article.image = e_form.cleaned_data['image']
			article.save()
			edit.delete()
			messages.add_message(request, messages.SUCCESS, message = 'Правки были приняты!')
			return redirect('main:home')
	else:
		form = form_class(instance = edit)
		context = {'edit':edit, 'article':article, 'form':form}
		return render(request, 'main/edit_detail.html', context)



@staff_member_required
def edit_list(request, pk):
	article = Article.objects.get(pk = pk)
	edit_article = EditArticle.objects.filter(article = article)
	context = {'edit_article':edit_article, 'article':article}
	return render(request, 'main/edit_list.html', context)





# Create your views here.

wiki/main/templates/main/add_article.html
{% extends 'layout/basic.html' %}


{% load bootstrap4 %}

{% block title %}Создание статьи{% endblock %}

{% block content %}
<h2>Создание статьи</h2>
<form method = 'post' enctype="multipart/form-data">
	{% csrf_token %}
	{% bootstrap_form forms %}
	{% bootstrap_formset formset %}
	{% buttons submit='Создать' %}{% endbuttons %}
</form>
{% endblock %}

wiki/main/templates/main/article_change_staff.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}
{% load crispy_forms_tags %}

{% block title %}Изменить{% endblock %}

{% block content %}
	<div class = 'text ml-3 p-3'>
		<form method = 'post' enctype="multipart/form-data">
			{% csrf_token %}
			{{ form|crispy }}
			{{ formset|crispy }}
			{% buttons submit='Изменить' %}{% endbuttons %}
		</form>
	</div>
{% endblock %}

wiki/main/templates/main/article_change_user.html
{% extends 'layout/basic.html' %}

{% load crispy_forms_tags %}

{% block title %}Изменение статьи{% endblock %}

{% block content %}
<div class = 'text ml-3 p-3'>
	<h2>Правки для статьи</h2>
	<form method="post">
		{% csrf_token %}
		{% crispy form %}
	</form>
</div>
{% endblock %}

wiki/main/templates/main/article_delete.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title %}Удалить{% endblock %}

{% block content %}
<div class = 'text ml-3 p-3'>
	<h2>Удаление статьи</h2>
	<form method = 'post' class = 'my-3'>
		{% csrf_token %}
		{% buttons submit='Удалить' %}{% endbuttons %}
	</form>
</div>
{% endblock %}

wiki/main/templates/main/change_pass.html
{% extends 'layout/basic.html' %}

{% load crispy_forms_tags %}
{% load bootstrap4 %}

{% block title %}Сменить пароль{% endblock %}

{% block content %}
<div class = 'text ml-3 p-3'>
	<h2>Сменить пароль</h2>
	<form method = 'post'>
		{% csrf_token %}
		{{ form|crispy }}
		{% buttons submit='Сменить' %}{% endbuttons %}
	</form>
</div>
{% endblock %}

wiki/main/templates/main/change_user_info.html
{% extends 'layout/basic.html' %}

{% load crispy_forms_tags %}

{% block title %}Изменить Данные{% endblock %}

{% block content %}
<div class = 'text ml-3 p-3'>
	<h2>Изменить Данные</h2>
	<form method="post">
		{% csrf_token %}
		{% crispy form %}
	</form>
</div>
{% endblock %}

wiki/main/templates/main/comment_delete.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title %}Удалить комментарий{% endblock %}

{% block content %}
<div class = 'text ml-3 p-3'>
	<h2>Удалить комментарий пользователя "{{ comment.author }}" под статьёй "{{ comment.article.title }}"</h2>
	<h3>Содержание комментария: <br> "{{ comment.content }}"</h3>
	<form method = 'post' class = 'my-3'>
		{% csrf_token %}
		{% buttons submit='Удалить' %}{% endbuttons %}
	</form>
</div>
{% endblock %}

wiki/main/templates/main/delete_user.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title %}Удалить пользователя{% endblock %}

{% block content %}
<div class = 'text ml-3 p-3'>
	<h2>Удалить пользователя</h2>
	<form method = 'post' class = 'my-4'>
		{% csrf_token %}
		{% buttons submit='Удалить' %}{% endbuttons %}
	</form>	
</div>
{% endblock %}

wiki/main/templates/main/detail.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}
{% load crispy_forms_tags %}

{% block title %}Статья {{ article.title }}{% endblock %}

{% block content %}

<!-- Статья -->
<div class = 'text ml-3 p-3'>
<div class = 'container-fluid mt-3'>
	<div class = 'row'>
		{% if article.image %}
		<div class = 'col-md-auto'>
			<img class = 'main-image first-image' src="{{ article.image.url }}">
		</div>
		{% endif %}
		<div class = 'col'>
			<h5 class = 'text-right'><a href="{% url 'main:article_change_user' pk=article.pk %}">Исправить ошибку</a></h5>
			{% if user.is_staff %}
				<h5 class = 'text-right'><a href="{% url 'main:edit_list' pk=article.pk %}">Посмотреть правки</a></h5>
			{% endif %}
			<h2>{{ article.title }}</h2>
			<p>{{ article.rubric }}</p>
			<p>{{ article.content }}</p>
		</div>
	</div>
</div>
{% if ai %}
<div class = 'col-md-auto d-flex justify-content-between dlex-wrap mt-5 '>
	{% for a in ai %}
	<div>
		<img class = 'additional-image' src="{{ a.image.url }}">
	</div>
	{% endfor %}
</div>
{% endif %}

<!-- Комментарии -->
<h4 class = 'mt-5'>Новый комментарий</h4>
{% if user.is_authenticated %}
	<form method="post">
		{% csrf_token %}
		{{ form|crispy }}
		{% buttons submit='Оставить комментарий' %}{% endbuttons %}
	</form>
{% else %}
	<p>Чтобы оставлять комментарии на статьях нужно зайти в аккаунт</p>
	<p><a href="{% url 'main:login' %}">Войти</a></p>
{% endif %}
{% if comment %}
<div class = 'mt-5'>
	{% for comm in comment %}
	<div class = 'my-2 p-2 border'>
		<h5>{{ comm.author }}</h5>
		<p>{{ comm.content }}</p>
		<p class = 'text-right font-italic'>{{ comm.created_at }}</p>
 		{% if user.username == comm.author %}
 			<a href="{% url 'main:comment_delete' pk=comm.pk %}">Удалить</a> 
 		{% elif user.is_staff %}
 			<a href="{% url 'main:comment_delete' pk=comm.pk %}">Удалить</a> 
 		{% endif %}
	</div>
	{% endfor %}
	{% endif %}
</div>
</div>
{% endblock %}

wiki/main/templates/main/edit_list.html
{% extends 'layout/basic.html' %}

{% load static %}
{% load thumbnail %}

{% block title %}Правки{% endblock %}

{% block content %}
	<h2 class = 'text my-3 p-3'>Все правки для статьи: "{{ article.title }}"</h2>
	{% if edit_article %}
		<ul class = 'list-unstyled'>
			{% for edits in edit_article %}
			<a href="{% url 'main:edit_detail' pk=edits.pk%}">
				<li class = 'my-3 media text p-3'>
					<p>
						{% if edits.image %}
							{% thumbnail edits.image 'default' as timg %}
							<img src="{{ timg.url }}" class = 'mr-5 main-image first-image'>
						{% else %}
							<p></p>
						{% endif %}
					</p>
					<div class = 'media-body'>
							<h3><p>{{ edits.title }}</p></h3> 
						<div>{{ edits.content }}</div>
					</div>
				</li>
			</a>
			{% endfor %}
		</ul>		
	{% endif %}
{% endblock %}

wiki/main/templates/main/logout.html
{% extends 'layout/basic.html' %}

{% block title %}Выход{% endblock %}

{% block content %}
	<div class = 'text ml-3 p-3'>
		<h2>Выход</h2>
		<p>Вы вышли из аккаунта</p>
	</div>
{% endblock %}

wiki/main/templates/main/password_reset_confirm.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}
{% load crispy_forms_tags %}

{% block title %}Сброс пароля{% endblock %}

{% block content %}
<div class = 'text ml-3 p-3'>
	<h2>Сброс пароля</h2>
	<form method="post">
		{% csrf_token %}
		{{ form|crispy }}
		{% buttons submit='Сбросить пароль' %}{% endbuttons %}
	</form>
</div>
{% endblock %}

wiki/main/templates/main/password_reset_form.html
{% extends 'layout/basic.html' %}

{% load crispy_forms_tags %}
{% load bootstrap4 %}

{% block title %}Сброс пароля{% endblock %}

{% block content %}
<div class = 'text ml-3 p-3'>
	<h2>Письмо для сброса пароля</h2>
	<form method="post">
		{% csrf_token %}
		{{ form|crispy }}
		{% buttons submit='Отправить письмо' %}{% endbuttons %}
	</form>
{% endblock %}

wiki/main/templates/main/register.html
{% extends 'layout/basic.html' %}

{% load crispy_forms_tags %}

{% block title %}Регистрация{% endblock %}

{% block content %}
	<div class = 'text ml-3 p-3'>
		<h2>Регистрация</h2>
		{% if user.is_authenticated %}
			<p>Чтобы выполнить регистрацию вы должны сначала выйти</p>
			<p><a href="{% url 'main:logout' %}">Выйти из аккаунта</a></p>
		{% else %}
			<form method = 'post'>
				{% csrf_token %}
				{% crispy form %}
			</form>
			<p class = 'my-3'><a href="{% url 'main:login' %}">Войти</a></p>
			<p><a href="{% url 'social:begin' 'vk-oauth2' %}">Войти через ВКонтакте</a></p>
		{% endif %}
	</div>
{% endblock %}